#!/usr/bin/env bash

set -e
set -o pipefail

[[ -z "${KUBE_FZF_PATH}" ]] && source kube-fzf.sh || source $KUBE_FZF_PATH
viewsecret() {
  local namespace_query pod_query result namespace pod_name

  _kube_fzf_handler "viewsecret" "$@"
  namespace_query=$(echo $args | awk -F '|' '{ print $1 }')
  secret_query=$(echo $args | awk -F '|' '{ print $2 }')

  result=$(_kube_fzf_search_secret "$namespace_query" "$secret_query")
  IFS=$'|' read -r namespace secret_name <<< "$result"

  _kube_fzf_echo "kubectl view-secret $secret_name --namespace='$namespace'"
  kubectl view-secret -a $secret_name --namespace=$namespace
}

viewsecret "$@"
